/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.Configuracao;
import Classes.ConfiguracaoControl;
import Classes.Registro;
import Classes.RegistroControl;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jean
 */
public class JanelaPrincipal extends javax.swing.JFrame {

    Configuracao configuracao;
    ConfiguracaoControl controle;

    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        this.setExtendedState(this.MAXIMIZED_BOTH);
        initComponents();
        URL url = this.getClass().getResource("/Interfaces/images/icons/icon.png");
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
        jButton_novo.setIcon(new ImageIcon(getClass().getResource("/Interfaces/images/icons/New/New_16x16.png")));
        jButton_buscar.setIcon(new ImageIcon(getClass().getResource("/Interfaces/images/icons/Search/Search_16x16.png")));
        jButton_configuracoes.setIcon(new ImageIcon(getClass().getResource("/Interfaces/images/icons/Settings/Settings_16x16.png")));
        jButton_abredir.setIcon(new ImageIcon(getClass().getResource("/Interfaces/images/icons/Open/Open_16x16.png")));
        jTable_registros.setAutoCreateRowSorter(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jButton_novo = new javax.swing.JButton();
        jButton_buscar = new javax.swing.JButton();
        jButton_configuracoes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton_abredir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_registros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MASL - My Anime and Serie List");
        setLocation(new java.awt.Point(150, 150));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));

        jButton_novo.setToolTipText("Novo registro");
        jButton_novo.setBorderPainted(false);
        jButton_novo.setContentAreaFilled(false);
        jButton_novo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton_novo.setFocusable(false);
        jButton_novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_novoMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_novoMouseEntered(evt);
            }
        });
        jButton_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novoActionPerformed(evt);
            }
        });

        jButton_buscar.setToolTipText("Buscar um registro");
        jButton_buscar.setBorderPainted(false);
        jButton_buscar.setContentAreaFilled(false);
        jButton_buscar.setFocusable(false);
        jButton_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_buscarMouseExited(evt);
            }
        });
        jButton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_buscarActionPerformed(evt);
            }
        });

        jButton_configuracoes.setToolTipText("Configurações do programa");
        jButton_configuracoes.setBorderPainted(false);
        jButton_configuracoes.setContentAreaFilled(false);
        jButton_configuracoes.setFocusable(false);
        jButton_configuracoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_configuracoesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_configuracoesMouseEntered(evt);
            }
        });
        jButton_configuracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_configuracoesActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Carregando...");

        jButton_abredir.setToolTipText("Abrir diretório com seus animes/séries (se já foi configurado)");
        jButton_abredir.setBorderPainted(false);
        jButton_abredir.setContentAreaFilled(false);
        jButton_abredir.setFocusable(false);
        jButton_abredir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_abredirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_abredirMouseEntered(evt);
            }
        });
        jButton_abredir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_abredirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_abredir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_configuracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 807, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_novo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jButton_abredir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jButton_configuracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jTable_registros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Tipo", "Ano", "Temporada", "Nota", "Gêneros", "Episódios", "Último assistido", "Última modificação", "Dropado?"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_registros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_registrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_registros);
        if (jTable_registros.getColumnModel().getColumnCount() > 0) {
            jTable_registros.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable_registros.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTable_registros.getColumnModel().getColumn(3).setPreferredWidth(5);
            jTable_registros.getColumnModel().getColumn(5).setPreferredWidth(5);
            jTable_registros.getColumnModel().getColumn(9).setPreferredWidth(100);
        }

        jMenu1.setText("Arquivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Novo registro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Configurações");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setText("Abrir diretório de animes e séries");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem4.setText("Sair");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Buscar");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ajuda");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        RegistroControl dadosiniciais = new RegistroControl();
        ArrayList<Registro> array = dadosiniciais.selectAll("id");
        montaTabelaPrincipal(array);
    }//GEN-LAST:event_formWindowGainedFocus

    private void jTable_registrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_registrosMouseClicked
        jTable_registros.setRowSelectionAllowed(true);
        if (evt.getClickCount() == 2) {
            System.out.println(jTable_registros.getValueAt(jTable_registros.getSelectedRow(), jTable_registros.getSelectedColumn()));
            new JanelaDetalhes((int) jTable_registros.getValueAt(jTable_registros.getSelectedRow(), 0)).setVisible(true);
        }
    }//GEN-LAST:event_jTable_registrosMouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        new JanelaCadastro().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton_configuracoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_configuracoesMouseEntered
        jButton_configuracoes.setBorderPainted(true);
        jButton_configuracoes.setContentAreaFilled(true);
        jButton_configuracoes.setOpaque(true);
        jButton_configuracoes.setFocusPainted(true);
    }//GEN-LAST:event_jButton_configuracoesMouseEntered

    private void jButton_configuracoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_configuracoesMouseExited
        jButton_configuracoes.setBorderPainted(false);
        jButton_configuracoes.setContentAreaFilled(false);
        jButton_configuracoes.setOpaque(false);
        jButton_configuracoes.setFocusPainted(false);
    }//GEN-LAST:event_jButton_configuracoesMouseExited

    private void jButton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_buscarActionPerformed
        new JanelaBusca().setVisible(true);
    }//GEN-LAST:event_jButton_buscarActionPerformed

    private void jButton_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscarMouseEntered
        jButton_buscar.setBorderPainted(true);
        jButton_buscar.setContentAreaFilled(true);
        jButton_buscar.setOpaque(true);
        jButton_buscar.setFocusPainted(true);
    }//GEN-LAST:event_jButton_buscarMouseEntered

    private void jButton_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_buscarMouseExited
        jButton_buscar.setBorderPainted(false);
        jButton_buscar.setContentAreaFilled(false);
        jButton_buscar.setOpaque(false);
        jButton_buscar.setFocusPainted(false);
    }//GEN-LAST:event_jButton_buscarMouseExited

    private void jButton_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novoActionPerformed
        new JanelaCadastro().setVisible(true);
    }//GEN-LAST:event_jButton_novoActionPerformed

    private void jButton_novoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_novoMouseEntered
        jButton_novo.setBorderPainted(true);
        jButton_novo.setContentAreaFilled(true);
        jButton_novo.setOpaque(true);
        jButton_novo.setFocusPainted(true);
    }//GEN-LAST:event_jButton_novoMouseEntered

    private void jButton_novoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_novoMouseExited
        jButton_novo.setBorderPainted(false);
        jButton_novo.setContentAreaFilled(false);
        jButton_novo.setOpaque(false);
        jButton_novo.setFocusPainted(false);
    }//GEN-LAST:event_jButton_novoMouseExited

    private void jButton_configuracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_configuracoesActionPerformed
        new JanelaConfiguracao().setVisible(true);
    }//GEN-LAST:event_jButton_configuracoesActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new JanelaConfiguracao().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new JanelaSobre().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new JanelaBusca().setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jButton_abredirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_abredirMouseExited
        jButton_abredir.setBorderPainted(false);
        jButton_abredir.setContentAreaFilled(false);
        jButton_abredir.setOpaque(false);
        jButton_abredir.setFocusPainted(false);
    }//GEN-LAST:event_jButton_abredirMouseExited

    private void jButton_abredirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_abredirMouseEntered
        jButton_abredir.setBorderPainted(true);
        jButton_abredir.setContentAreaFilled(true);
        jButton_abredir.setOpaque(true);
        jButton_abredir.setFocusPainted(true);
    }//GEN-LAST:event_jButton_abredirMouseEntered

    private void jButton_abredirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_abredirActionPerformed
        abreDir();
    }//GEN-LAST:event_jButton_abredirActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       abreDir();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        <editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        </editor-fold>

        try {
            javax.swing.UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_abredir;
    private javax.swing.JButton jButton_buscar;
    private javax.swing.JButton jButton_configuracoes;
    private javax.swing.JButton jButton_novo;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_registros;
    // End of variables declaration//GEN-END:variables

    void montaTabelaPrincipal(ArrayList<Registro> array) {
        DefaultTableModel modelo = (DefaultTableModel) jTable_registros.getModel();
        //if (!array.isEmpty()) {
        int rowCount = modelo.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            modelo.removeRow(i);
        }
        for (Registro registro : array) {
            modelo.addRow(new Object[]{registro.getId(), registro.getNome(), registro.getTipo(), registro.getAno(), registro.getTemporada(), registro.getNota(), registro.getGeneros(), registro.getEpitotal(), registro.getEpiatual(), registro.getUltimaModificacao(), registro.getDrop()});
        }
        jTable_registros.getSelectionModel().setSelectionInterval(0, 0);
        jTable_registros.setModel(modelo);
        //}

        jTable_registros.getColumnModel().getColumn(0).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(1).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(2).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(3).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(4).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(5).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(6).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(7).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(8).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(9).setCellRenderer(new IconifiedRenderer());
        jTable_registros.getColumnModel().getColumn(10).setCellRenderer(new IconifiedRenderer());

        jTable_registros.setRowSelectionAllowed(false);

        controle = new ConfiguracaoControl();
        configuracao = new Configuracao();
        configuracao.setUserName(controle.setaUserName());

        if ("default".equals(configuracao.getUserName())) {
            jLabel1.setText("Seja bem vindo! Defina um nome de usuário em configurações!");
        } else {
            jLabel1.setText("Lista de animes e séries de " + configuracao.getUserName());
        }
    }

    private void abreDir() {
        Properties properties = System.getProperties();
        System.out.println("propriedades: " + properties.toString());
        System.out.println(System.getProperty("os.name"));
        String so = String.valueOf(System.getProperty("os.name"));
        System.out.println("O sistema operacional é: " + so);

        controle = new ConfiguracaoControl();
        configuracao = new Configuracao();
        configuracao.setDir(controle.setaDir());

        if (so.equals("Linux")) {
            try {
                System.out.println("Tentando gerenciador de arquivos nautilus");
                Runtime.getRuntime().exec("nautilus " + configuracao.getDir());
            } catch (IOException ex) {
                System.out.println("Tentando gerenciador de arquivos nemo");
                try {
                    Runtime.getRuntime().exec("nemo " + configuracao.getDir());
                } catch (IOException ex1) {
                    System.out.println("Tentando gerenciador de arquivos konquerer");
                    try {
                        Runtime.getRuntime().exec("konquerer " + configuracao.getDir());
                    } catch (IOException ex2) {
                        System.out.println("Tentando gerenciador de arquivos dolphin");
                        try {
                            Runtime.getRuntime().exec("dolphin " + configuracao.getDir());
                        } catch (IOException ex3) {
                            System.out.println("ERRO nenhum dos gerenciadores de arquivos acima foram encontrados!");
                        }
                    }
                }
            }
        } else {
            try {
                Runtime.getRuntime().exec("explorer " + configuracao.getDir());
            } catch (IOException ex) {
                System.out.println("Erro ao executar o Explorer do Windows");
            }
        }
    }
}
